### ISSUE TITLE
How can I include and use this library?

### ISSUE THREAD

**Issue by abhinavzspace** [powet/elm-pouchdb#1]
Hi

This seems to be an awesome effort. I really need to use pouchdb in my elm code. Is this usable?

Few concerns I was having:
1. Is it published on package manager?
2. This library is using version 5 of pouchdb which is included directly. Should one be concerned about that?

I am very new to elm world. Just been 1 week tinkering around with small pieces of code. Liking it so far though!

I have forked it. So far was able to run examples successfully except the ReplicateExample.elm.

**Comment by eticav** [comment]
Hi,

elm-pouchdb was only released a couple of months ago. It is quite new. It is the first real effort for mapping pouchdb in elm. Any feedback is very useful, thanks again. 
It is usable( really at your own risk), 95% of the pouchdb functionalities have been mapped. I will be using it on a rather big application in December therefor I'll be paying extra attention on the quality here. Again any help from the users are very helpful.

It contains several Native code files which has the following consequences:
1. It has to be checked by elm team before being pushed to in the package manager.
2. Native package Names were named using the  pattern _user$project$Native..., but should really be named as _powet$elm_pouchdb$Native_..... I will be pushing this proper naming in the next version. This means that you will have to put manually elm-pouchdb in yout elm-stuff directory. This will not be handy for the users for we're stuck here till the package is validated by the elm-team. 

Can you provide any error messages you have as I not been able to reproduce the bug on ReplicateExample.elm?

**Comment by abhinavzspace** [comment]
I am getting the following error while running ReplicateExample.elm through elm reactor in example directory.

`Uncaught TypeError: Cannot read property 'ctor' of undefined`

I am deciding between react-redux and elm for my next project which will require pouch/couch as the database. I am very impressed by elm language and may be it will pay off in the future if I choose elm from the start. 

So the point is I would really like to use this library and as early as possible. I don't care how I include the library and if it's on packages at elm hub.

May be I can help somehow in development by providing you with stack traces during errors and try submitting any pull requests when I get used to elm and the ecosystem later on.

But for now, can you give me some quick tricks to include it in my basic boilerplate? I will try changing Native package names as you suggested. May be that will work.

Cheers!

**Comment by abhinavzspace** [comment]
And also I was wondering (general question, out of topic) that why is everybody (elmfire, d3 port, etc) implementing in native code, even though everywhere I read they say that it is not the best way to go about it. Are there some serious benefits? :)

**Comment by eticav** [comment]
Bug is now corrected in the branch 
https://github.com/powet/elm-pouchdb/tree/issue1

FYI, the events(pause, active, error, denied, change, complete)  coming from replication and sync do not carry any data, although in the pouchdb js they do.  I do not find dealing with the replication data of these events really useful because you're better off listening directly to "_changes" if you need the data. Still if you need to deal with such replication events, let me know (PR) and I'll put that in my TODO list.

**Comment by abhinavzspace** [comment]
`ReplicateExample.elm` is working fine now. Thanks!

And I was able to put the whole elm-pouchdb package in my project folder and run examples smoothly. 👍

**Comment by eticav** [comment]
Don't hesitate if any issues or any questions.
Thanks!

**Comment by asianfilm** [comment]
In the first comment here, @abhinavzspace asked whether s/he should be concerned that PouchDB 5.x is wired in directly. From my limited experience with the library, it's working fine if you replace it with PouchDB 6.1. I wasn't able to upgrade TestHelpers.elm to Elm 0.18 - which would let one run the test suite and be sure there are no edge cases. For someone with more Elm skills than me, that part of the code be worth updating in case it's holding up the inclusion in the Elm package manager. There's a great post **[here](https://becoming-functional.com/tasks-in-elm-0-18-2b64a35fd82e#.3wkwfkoy4)** on updating Tasks to Elm 0.18 that may help; I only got so far in my own attempts.

And, this isn't the right place, but I want to thank @powet for the beautifully written code, the inclusion of useful examples, and the prompt upgrade to 0.18.

**Comment by dvberkel** [comment]
> This means that you will have to put manually elm-pouchdb in your elm-stuff directory.

I will document the steps when I interpreted the above comment. Hopefully this will help people before `elm-pouchdb` gets adopted as [elm-package](http://package.elm-lang.org/).

1. Use npm to install `powet/elm-pouchdb`
2. Create the following directories under `elm-stuff/packages`: `packages/powet/elm-pouchdb/<VERSION>` where `<VERSION>` should be as documented by elm-pouchdb `elm-package.json`. For me that was  `1.0.5`.
3. Copy the contents of `node_modules/elm-pouchdb` directory to the aforementioned directory.
4. Toggle the name comments in all the native modules: `ElmPouchdbChange.js`, `ElmPouchdbEvents.js`, `ElmPouchdb.js` and `ElmPouchdbReplicate.js`. For example, the top of `ElmPouchdbChange.js` should look like

```javascript
'use strict';

var _powet$elm_pouchdb$Native_ElmPouchdbChange = function() {
// var _user$project$Native_ElmPouchdbChange = function() {
```

5. Add an entry to `elm-stuff/exact-dependencies.json` detailing the `elm-pouchdb` package. For me that was

```json
  "powet/elm-pouchdb": "1.0.5"
```

6. Add a dependency  to your `elm-package.json`. Again for me that was

```json
  "powet/elm-pouchdb": "1.0.0 <= v < 2.0.0"
```
