### ISSUE TITLE
0.19 port

### ISSUE THREAD

**Issue by bidigo** [powet/elm-pouchdb#13]
Any plans to port this library to support the newly released elm 0.19?

**Comment by eticav** [comment]
Hi Bidigo,
I will not  be maintaining this library anymore. Sorry for that! The main reason is that elm team will not integrate this library into their elm libraries, because elm-pouchdb contains js code.

Thanks

**Comment by bidigo** [comment]
Hi Etienne,

thanks for the info, that's fair enough.

**Comment by daveman1010221** [comment]
@eticav could you elaborate on what the issue is? Would it be worth my time to port this to pure elm? REALLY need a pouch adapter for elm. Thanks.

**Comment by daveman1010221** [comment]
I see the code uses native binding quite a lot. Is that the problem? I read somewhere that starting with elm .19, no more native, except for the core team?
